spring.application.name=CategoryService
spring.profiles.active=MySQl
project.path=allimages/
#screte value any complex logic
spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
#Expiration value in ms
spring.app.jwtExpirationMs=3000000
#spring.app.jwtExpirationMs=30000
spring.app.jwtSpringCookie=springCookie
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project.CategoryService=DEBUG
