#spring.application.name=CategoryService
#spring.profiles.active=H2,SQL

#To enable H2 dB
spring.h2.console.enabled=true

#Without this every server restart will generate new URL which everytime needs to be feed to h2 console\
#  jdbc:h2:mem:d352e179-de6b-4ae0-a85c-52e7a0032ec5 - samle of URL generated
spring.datasource.url=jdbc:h2:mem:test

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update