#spring.application.name=CategoryService
#spring.profiles.active=H2,SQL

#To enable H2 dB
spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:test
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update